# Generated by Django 5.1.2 on 2024-10-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'ordering': ['-titulo', '-data_publicacao'], 'permissions': (('can_drive', 'Can drive'), ('can_vote', 'Can vote in elections'), ('can_drink', 'Can drink alcohol')), 'verbose_name_plural': 'Artigos'},
        ),
    ]
