# Generated by Django 5.1.2 on 2024-10-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_artigo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artigo',
            options={'ordering': ['-titulo', '-data_publicacao'], 'verbose_name_plural': 'Artigos'},
        ),
    ]
