# Generated by Django 5.1.2 on 2024-10-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_is_admin_alter_account_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('can_manage_user', 'Pode gerenciar Usuarios e Grupos'), ('can_test_things', 'Pode testar essa coisa aqui'))},
        ),
    ]
